/**
 * 构建脚本：将 src/agent/roles/ 目录下所有内置角色的 YAML 文件
 * 读取后生成 src/generated/bundledRoles.ts，供 Bun 打包时嵌入二进制。
 *
 * 使用方式：bun run scripts/embedRoles.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';

const scriptDir = import.meta.dir;
const rolesDir = join(scriptDir, '../src/agent/roles');
const outputPath = join(scriptDir, '../src/generated/bundledRoles.ts');

if (!existsSync(rolesDir)) {
  console.error(`❌ roles 目录不存在: ${rolesDir}`);
  process.exit(1);
}

interface RoleFile {
  name: string;      // role folder name, e.g. "supervisor"
  content: string;   // raw YAML content
}

const roles: RoleFile[] = [];

for (const entry of readdirSync(rolesDir)) {
  const fullPath = join(rolesDir, entry);
  if (!statSync(fullPath).isDirectory()) continue;

  const configPath = join(fullPath, 'config.yaml');
  if (!existsSync(configPath)) {
    console.warn(`⚠️  跳过角色 "${entry}"：缺少 config.yaml`);
    continue;
  }

  const content = readFileSync(configPath, 'utf8');
  roles.push({ name: entry, content });
}

mkdirSync(dirname(outputPath), { recursive: true });

let output = `// Auto-generated by scripts/embedRoles.ts — DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Total roles: ${roles.length}

export interface BundledRole {
  /** Role folder name, e.g. "supervisor" */
  name: string;
  /** Raw YAML content of config.yaml */
  content: string;
}

export const BUNDLED_ROLES: BundledRole[] = [
`;

for (const role of roles) {
  output += `  { name: ${JSON.stringify(role.name)}, content: ${JSON.stringify(role.content)} },\n`;
}

output += `];\n`;

writeFileSync(outputPath, output);
console.log(`  ✓ ${roles.map(r => r.name).join(', ')}`);
console.log(`\n✅ 嵌入 ${roles.length} 个内置角色 → ${outputPath}`);
