import { $ } from 'bun';
import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';

const external = ['electron', 'chromium-bidi', 'cpu-features', 'playwright', 'playwright-core']

const targets: Record<string, { target: string; outfile: string; flags?: string[] }> = {
  default: { target: 'bun', outfile: 'dist/clawgoal-server', flags: ['--sourcemap'] },
  'linux-arm64': { target: 'bun-linux-arm64', outfile: 'dist/clawgoal-server-linux-arm64', flags: ['--sourcemap', '--static'] },
  'linux-x64': { target: 'bun-linux-x64-musl', outfile: 'dist/clawgoal-server-linux-amd64', flags: ['--sourcemap', '--static'] },
  'mac-arm64': { target: 'bun-darwin-arm64', outfile: 'dist/clawgoal-server-mac-arm64', flags: ['--sourcemap'] },
  'mac-x64': { target: 'bun-darwin-x64', outfile: 'dist/clawgoal-server-mac-x64', flags: ['--sourcemap'] },
  'win-x64': { target: 'bun-windows-x64', outfile: 'dist/clawgoal-server-win-x64.exe', flags: ['--sourcemap'] },
  'win-arm64': { target: 'bun-windows-arm64', outfile: 'dist/clawgoal-server-win-arm64.exe', flags: ['--sourcemap'] },
  'win-arm64-native': { target: 'bun', outfile: 'dist/clawgoal-server-win-arm64.exe', flags: ['--sourcemap'] },
}

// platformNameMap: key（build.ts 的参数） → 平台名（BUILD_ID 用）
const platformNameMap: Record<string, string> = {
  'linux-arm64': 'linux-arm64',
  'linux-x64': 'linux-amd64',
  'mac-arm64': 'darwin-arm64',
  'mac-x64': 'darwin-amd64',
  'win-x64': 'windows-amd64',
  'win-arm64': 'windows-arm64',
  'win-arm64-native': 'windows-arm64',
}

// 生成 BUILD_ID
function ts(): string {
  const n = new Date()
  return `${n.getFullYear()}${String(n.getMonth()+1).padStart(2,'0')}${String(n.getDate()).padStart(2,'0')}-${String(n.getHours()).padStart(2,'0')}${String(n.getMinutes()).padStart(2,'0')}${String(n.getSeconds()).padStart(2,'0')}`
}
function buildIdForTarget(key: string): string {
  // 已知目标平台
  const plat = platformNameMap[key]
  if (plat) return `${plat}-${ts()}`
  // 兜底：当前运行平台
  const p = process.platform.replace('win32', 'windows')
  const a = process.arch.replace('x64', 'amd64')
  return `${p}-${a}-${ts()}`
}

const key = process.argv[2] ?? 'default'
const cfg = targets[key]
if (!cfg) {
  console.error(`Unknown target: ${key}. Available: ${Object.keys(targets).join(', ')}`)
  process.exit(1)
}

const externalArgs = external.flatMap(e => ['--external', e])
const extraFlags = cfg.flags ?? []

// BUILD_SOURCEMAP_ENABLE 环境变量控制是否将 sourcemap 嵌入二进制
// 设为 false/0 可在构建时跳过 sourcemap 以减小二进制体积（默认嵌入）
const sourcemapEnabled = process.env.BUILD_SOURCEMAP_ENABLE !== 'false' && process.env.BUILD_SOURCEMAP_ENABLE !== '0'
const filteredFlags = sourcemapEnabled ? extraFlags : extraFlags.filter(f => f !== '--sourcemap')

// BUILD_ID：环境变量（CI/workflow 传入）> 根据目标平台自动生成
const buildId = process.env.BUILD_ID || buildIdForTarget(key)
const buildIdFile = 'src/generated/buildId.ts'
mkdirSync(dirname(buildIdFile), { recursive: true })
writeFileSync(buildIdFile, `// Auto-generated by build.ts — DO NOT EDIT
export const BUILD_ID = '${buildId}';\n`)
console.log(`✅ buildId.ts 已生成: BUILD_ID=${buildId}`)

// 生成 buildSourcemap.ts（构建时确定的 sourcemap 状态）
const buildSourcemapFile = 'src/generated/buildSourcemap.ts'
writeFileSync(buildSourcemapFile, `// Auto-generated by build.ts — DO NOT EDIT
export const BUILD_SOURCEMAP_ENABLED = ${sourcemapEnabled};\n`)
console.log(`✅ buildSourcemap.ts 已生成: BUILD_SOURCEMAP_ENABLED=${sourcemapEnabled}`)

await $`bun run scripts/embedUi.ts`
await $`bun run scripts/genApiDoc.ts`
await $`bun build src/cli.ts --production --compile --outfile ${cfg.outfile} --minify ${filteredFlags} --target=${cfg.target} --loader .yaml:text --loader .png:file ${externalArgs}`
