/**
 * 构建脚本：将所有静态文件编码为 base64，
 * 生成 src/generated/uiAssets.ts，供 Bun 打包时嵌入二进制。
 *
 * 使用方式：bun run scripts/embedUi.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { dirname, extname, join, relative } from 'path';

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.map': 'application/json',
  '.txt': 'text/plain',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
};

interface EmbeddedFile {
  path: string;
  mimeType: string;
  data: string; // base64
}

function walkDir(dir: string, baseDir: string): EmbeddedFile[] {
  const files: EmbeddedFile[] = [];
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...walkDir(fullPath, baseDir));
    } else {
      const ext = extname(entry).toLowerCase();
      if (ext === '.map') continue; // sourcemap 已移至 _temp/<BUILD_ID>/
      const relativePath = '/' + relative(baseDir, fullPath).replace(/\\/g, '/');
      const mimeType = MIME_TYPES[ext] ?? 'application/octet-stream';
      const data = readFileSync(fullPath).toString('base64');
      files.push({ path: relativePath, mimeType, data });
    }
  }

  return files;
}

const scriptDir = import.meta.dir;
const uiDistDir = join(scriptDir, '../../ui/dist');
const outputPath = join(scriptDir, '../src/generated/uiAssets.ts');

if (!existsSync(uiDistDir)) {
  console.error(`❌ ui/dist 目录不存在: ${uiDistDir}`);
  console.error('请先运行前端构建：pnpm --filter @clawgoal/ui build');
  process.exit(1);
}

console.log(`📂 扫描: ${uiDistDir}`);
const files = walkDir(uiDistDir, uiDistDir);

// Compute a content-based BUILD_ID so the binary can detect if tmp files are stale
let _hash = 5381;
for (const f of files) {
  for (let i = 0; i < f.path.length; i++) {
    _hash = ((_hash << 5) + _hash + f.path.charCodeAt(i)) | 0;
  }
  _hash = ((_hash << 5) + _hash + f.data.length) | 0;
}
const buildId = Math.abs(_hash).toString(36);

mkdirSync(dirname(outputPath), { recursive: true });

let output = `// Auto-generated by scripts/embedUi.ts — DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Total files: ${files.length}

export const BUILD_ID = '${buildId}';

export interface EmbeddedFile {
  data: string;    // base64 encoded content
  mimeType: string;
}

export const embeddedFiles = new Map<string, EmbeddedFile>([
`;

for (const file of files) {
  output += `  [${JSON.stringify(file.path)}, { mimeType: ${JSON.stringify(file.mimeType)}, data: ${JSON.stringify(file.data)} }],\n`;
}

output += `]);\n`;

writeFileSync(outputPath, output);
console.log(`✅ 嵌入 ${files.length} 个文件 → ${outputPath}`);
