export const EXTRA_PERMISSION_OPTIONS = [
  {
    label: '通知渠道',
    options: [
      { label: '通知渠道列表', value: 'claw/channel/list' },
      { label: '添加通知渠道', value: 'claw/channel/add' },
      { label: '修改通知渠道', value: 'claw/channel/edit' },
      { label: '删除通知渠道', value: 'claw/channel/delete' },
      { label: '启用/禁用通知渠道', value: 'claw/channel/toggleEnable' },
      { label: '测试通知渠道', value: 'claw/channel/testSend' },
    ],
  },
  {
    label: 'Agent',
    options: [
      { label: '角色列表', value: 'claw/agent/roles/list' },
      { label: '角色详情', value: 'claw/agent/roles/detail' },
      { label: 'Agent 列表', value: 'claw/agent/list' },
      { label: '活跃 Agent 列表', value: 'claw/agent/activeList' },
      { label: 'Agent 详情', value: 'claw/agent/detail' },
      { label: '添加 Agent', value: 'claw/agent/add' },
      { label: '设置 Agent 活跃状态', value: 'claw/agent/setActive' },
      { label: '删除 Agent', value: 'claw/agent/remove' },
      { label: '修改 Agent 基本信息', value: 'claw/agent/updateBasic' },
      { label: '修改 Agent 配置', value: 'claw/agent/updateConfig' },
      { label: 'Agent 状态', value: 'claw/agent/status' },
      { label: 'Agent 角色配置', value: 'claw/agent/roleConfig' },
    ],
  },
  {
    label: '运行环境',
    options: [
      { label: '运行环境列表', value: 'claw/runtime/list' },
      { label: '添加运行环境', value: 'claw/runtime/add' },
      { label: '修改运行环境', value: 'claw/runtime/edit' },
      { label: '删除运行环境', value: 'claw/runtime/delete' },
    ],
  },
  {
    label: '定时',
    options: [
      { label: '任务列表', value: 'claw/cron/list' },
      { label: '调度统计', value: 'claw/cron/stat' },
      { label: '添加', value: 'claw/cron/add' },
      { label: '修改任务', value: 'claw/cron/update' },
      { label: '删除任务', value: 'claw/cron/delete' },
      { label: '启用/禁用任务', value: 'claw/cron/toggle' },
      { label: '立即执行', value: 'claw/cron/run' },
      { label: '执行日志', value: 'claw/cron/logs' },
      { label: '执行历史', value: 'claw/cron/history' },
      { label: '删除执行历史', value: 'claw/cron/history/delete' },
    ],
  },
  {
    label: 'MCP',
    options: [
      { label: 'MCP 列表', value: 'claw/mcp/list' },
      { label: 'MCP 详情', value: 'claw/mcp/detail' },
      { label: '添加 MCP', value: 'claw/mcp/add' },
      { label: '修改 MCP', value: 'claw/mcp/edit' },
      { label: '删除 MCP', value: 'claw/mcp/remove' },
      { label: '启用/禁用 MCP', value: 'claw/mcp/setEnable' },
    ],
  },
  {
    label: '目标管理',
    options: [
      { label: '目标项目列表', value: 'claw/objective/project/list' },
      { label: '添加目标项目', value: 'claw/objective/project/add' },
      { label: '修改目标项目', value: 'claw/objective/project/edit' },
      { label: '删除目标项目', value: 'claw/objective/project/delete' },
      { label: '添加目标项', value: 'claw/objective/item/add' },
      { label: '修改目标项', value: 'claw/objective/item/edit' },
      { label: '删除目标项', value: 'claw/objective/item/delete' },
      { label: '切换目标项状态', value: 'claw/objective/item/toggle' },
      { label: '专注任务列表', value: 'claw/objective/focus/list' },
      { label: '添加专注任务', value: 'claw/objective/focus/add' },
      { label: '修改专注任务', value: 'claw/objective/focus/edit' },
      { label: '删除专注任务', value: 'claw/objective/focus/delete' },
      { label: '专注任务状态', value: 'claw/objective/focus/status' },
    ],
  },
  {
    label: '配置项',
    options: [
      { label: '获取配置', value: 'claw/option/get' },
      { label: '批量获取配置', value: 'claw/option/getMulti' },
      { label: '设置配置', value: 'claw/option/set' },
      { label: '批量设置配置', value: 'claw/option/setMulti' },
    ],
  },
  {
    label: '项目',
    options: [
      { label: '项目列表', value: 'claw/project/list' },
      { label: '项目详情', value: 'claw/project/detail' },
      { label: '添加项目', value: 'claw/project/add' },
      { label: '修改项目', value: 'claw/project/edit' },
      { label: '删除项目', value: 'claw/project/delete' },
      { label: '事件列表', value: 'claw/project/event/list' },
      { label: '事件类型', value: 'claw/project/event/types' },
      { label: '添加事件', value: 'claw/project/event/add' },
      { label: '修改事件', value: 'claw/project/event/edit' },
      { label: '删除事件', value: 'claw/project/event/delete' },
    ],
  },
  {
    label: '项目指标',
    options: [
      { label: '指标列表', value: 'claw/metric/list' },
      { label: '添加指标', value: 'claw/metric/add' },
      { label: '修改指标', value: 'claw/metric/edit' },
      { label: '删除指标', value: 'claw/metric/delete' },
      { label: '指标项列表', value: 'claw/metric/item/list' },
      { label: '更新指标项', value: 'claw/metric/item/upsert' },
      { label: '批量更新指标项', value: 'claw/metric/item/batch' },
      { label: '删除指标项', value: 'claw/metric/item/delete' },
      { label: '指标汇总', value: 'claw/metric/item/summary' },
    ],
  },
  {
    label: '项目笔记',
    options: [
      { label: '笔记列表', value: 'claw/note/list' },
      { label: '笔记类型', value: 'claw/note/types' },
      { label: '添加笔记', value: 'claw/note/add' },
      { label: '修改笔记', value: 'claw/note/edit' },
      { label: '删除笔记', value: 'claw/note/delete' },
    ],
  },
  {
    label: '项目需求池',
    options: [
      { label: '需求列表', value: 'claw/backlog/list' },
      { label: '需求类型', value: 'claw/backlog/types' },
      { label: '添加需求', value: 'claw/backlog/add' },
      { label: '修改需求', value: 'claw/backlog/edit' },
      { label: '删除需求', value: 'claw/backlog/delete' },
      { label: '修改需求状态', value: 'claw/backlog/status' },
    ],
  },
  {
    label: '项目知识库',
    options: [
      { label: '知识库列表', value: 'claw/wiki/list' },
      { label: '获取知识库', value: 'claw/wiki/get' },
      { label: '添加知识库', value: 'claw/wiki/add' },
      { label: '修改知识库', value: 'claw/wiki/edit' },
      { label: '删除知识库', value: 'claw/wiki/delete' },
      { label: '知识库对话', value: 'claw/wiki/chat' },
    ],
  },
  {
    label: '技能',
    options: [
      { label: '技能列表', value: 'claw/skills/list' },
      { label: '技能详情', value: 'claw/skills/detail' },
      { label: '删除技能', value: 'claw/skills/delete' },
    ],
  },
  {
    label: '任务',
    options: [
      { label: '任务列表', value: 'claw/task/list' },
      { label: '任务详情', value: 'claw/task/detail' },
      { label: '删除任务', value: 'claw/task/delete' },
      { label: '停止任务', value: 'claw/task/stop' },
      { label: '重试任务', value: 'claw/task/retry' },
    ],
  },
  {
    label: '工具',
    options: [{ label: '工具列表', value: 'claw/tools/list' }],
  },
]
